name: Build ClickHouse Test Image

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - 'docker/clickhouse/**'
      - 'data/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cbioportal/clickhouse-test

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ClickHouse test data image
        run: |
          chmod +x docker/clickhouse/build.sh
          docker/clickhouse/build.sh ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Push image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
